### PR TITLE
Added `use_public_url` configuration option.

### PR DESCRIPTION
**Pull request by frol**
Not only it makes things fine-grain configurable, this also fixes an issue of uploading a new file when the `url` is not reachable.

### CODE REVIEW

**Comment by frol** [comment]
@utek Could you please review and release a new version of pyseaweed with this fix?

**Comment by frol** [comment]
@utek Do you plan a release soon?

**Comment by utek** [comment]
@frol Yes I am. I'm just really busy right now. Will try to release it today/tomorrow

**Comment by frol** [comment]
Thank you!

**Comment by frol** [comment]
I am sorry for bothering you, but it is just much easier for me to work with the released versions of packages, so I am kindly pinging you.

**Comment by utek** [comment]
@frol Thanks for reminding me. It's released

**Pull request merged**
